# Generated by Django 2.2.4 on 2019-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gradesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder', models.TextField(verbose_name='Builder')),
                ('admin', models.TextField(verbose_name='Administator')),
                ('vip', models.TextField(verbose_name='V.I.P')),
                ('scripter', models.TextField(verbose_name='Scripter')),
                ('mod', models.TextField(verbose_name='Moderator')),
                ('flyer', models.TextField(verbose_name='Flyer')),
            ],
        ),
    ]
