# Generated by Django 2.2.4 on 2019-09-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradesmodel',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='gradesmodel',
            name='builder',
        ),
        migrations.RemoveField(
            model_name='gradesmodel',
            name='flyer',
        ),
        migrations.RemoveField(
            model_name='gradesmodel',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='gradesmodel',
            name='scripter',
        ),
        migrations.RemoveField(
            model_name='gradesmodel',
            name='vip',
        ),
    ]
