# Generated by Django 2.2.4 on 2019-09-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190905_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gradesModel',
        ),
    ]
